export const FETCH_ALL_CAPSULES_START = "FETCH_ALL_CAPSULES_START";
export const FETCH_ALL_CAPSULES_SUCCESS = "FETCH_ALL_CAPSULES_SUCCESS";
export const FETCH_ALL_CAPSULES_FAILED = "FETCH_ALL_CAPSULES_FAILED";

export const CHANGE_LANDING_PAD_INPUT = "CHANGE_LANDING_PAD_INPUT";

export const FETCH_LANDING_PAD_START = "FETCH_LANDING_PAD_START";
export const FETCH_LANDING_PAD_SUCCESS = "FETCH_LANDING_PAD_SUCCESS";
export const FETCH_LANDING_PAD_FAILED = "FETCH_LANDING_PAD_FAILED";